// This file contains code autogenerated by DependencyKit.
// Do not modify.

import Combine
import DependencyKit
import Foundation

public extension ResourceType where I: NetworkClientRequirements {
    var networkMonitor: NetworkMonitorInterface? { injected.networkMonitor }
}
