// This file contains code autogenerated by DependencyKit.
// Do not modify.

import Combine
import DependencyKit
import Foundation
import NetworkClient
import QuartzCore
import SwiftUI

extension ResourceType where I: ScopeOneRequirements {
    var explicit: String { injected.explicit }
    var modified: String { injected.modified }
}

extension ResourceType where I: ScopeThreeRequirements {
    var createdLater: String { injected.createdLater }
    var duplicated: String { injected.duplicated }
    var explicit: String { injected.explicit }
    var implicit: String { injected.implicit }
    var modified: String { injected.modified }
    var optional: String? { injected.optional }
    var recreated: String { injected.recreated }
}

extension ResourceType where I: ScopeTwoRequirements {
    var createdLater: String { injected.createdLater }
    var explicit: String { injected.explicit }
    var modified: String { injected.modified }
    var recreated: String { injected.recreated }
}
